language: r
cache: packages
latex: false

before_install:
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev

jobs:
  include:
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("TBFmultinomial")'
    - Rscript -e 'remotes::install_cran("covr")'
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_cran("scam")'
    - Rscript -e 'remotes::install_cran("RColorBrewer")'
    - Rscript -e 'remotes::install_cran("timereg")'
    - Rscript -e 'remotes::install_cran("grid")'
    - Rscript -e 'remotes::install_cran("gridExtra")'
    - Rscript -e 'remotes::install_cran("coxme")'
    - Rscript -e 'remotes::install_cran("knitr")'
    - Rscript -e 'remotes::install_cran("rmarkdown")'
    - Rscript -e 'remotes::install_cran("pec")'
    - Rscript -e 'remotes::install_cran("devtools")'
    - Rscript -e 'remotes::install_cran("eha")'
    - Rscript -e 'remotes::install_cran("survival")'
    - Rscript -e 'remotes::install_github("cran/etm")'

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: false
  local_dir: docs
  on:
    all_branches: true
